import { Platform, StyleSheet } from "react-native";

export const COLORS = {
  bg: "#F7F4F0",
  ink: "#1F2328",
  muted: "#5B616A",
  card: "#FFFFFF",
  accent: "#0E7C86",
  accentSoft: "#D5F3F1",
  track: "#E3E0DA",
  soft: "#EFEAE4",
  coral: "#F5C8B8",
};

export const styles = StyleSheet.create({
  container: { flex: 1, padding: 16, backgroundColor: COLORS.bg },
  scrollContent: { paddingBottom: 0, flexGrow: 1 },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  bgOrbOne: {
    position: "absolute",
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: COLORS.accentSoft,
    top: -90,
    left: -50,
    opacity: 0.85,
  },
  bgOrbTwo: {
    position: "absolute",
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: COLORS.coral,
    bottom: -70,
    right: -50,
    opacity: 0.7,
  },
  header: { marginBottom: 14 },
  eyebrow: {
    fontSize: 12,
    letterSpacing: 2,
    color: COLORS.muted,
    fontWeight: "700",
    ...Platform.select({
      ios: { fontFamily: "AvenirNext-DemiBold" },
      android: { fontFamily: "sans-serif-medium" },
      default: {},
    }),
  },
  title: {
    fontSize: 32,
    fontWeight: "800",
    color: COLORS.ink,
    marginTop: 6,
    ...Platform.select({
      ios: { fontFamily: "AvenirNext-Heavy" },
      android: { fontFamily: "sans-serif-condensed" },
      default: {},
    }),
  },
  subtitle: {
    marginTop: 6,
    color: COLORS.muted,
    fontSize: 15,
    ...Platform.select({
      ios: { fontFamily: "AvenirNext-Regular" },
      android: { fontFamily: "sans-serif-light" },
      default: {},
    }),
  },
  card: {
    backgroundColor: COLORS.card,
    borderRadius: 20,
    padding: 18,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 4,
    borderWidth: 1,
    borderColor: "#F3EEE7",
  },
  phasePill: {
    alignSelf: "flex-start",
    backgroundColor: COLORS.accentSoft,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
  },
  phaseRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  phaseCaption: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.2,
    color: COLORS.muted,
    textTransform: "uppercase",
  },
  phaseLabel: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.2,
    color: COLORS.accent,
    ...Platform.select({
      ios: { fontFamily: "AvenirNext-DemiBold" },
      android: { fontFamily: "sans-serif-medium" },
      default: {},
    }),
  },
  countdown: {
    fontSize: 58,
    fontWeight: "800",
    marginTop: 12,
    marginBottom: 8,
    color: COLORS.ink,
    ...Platform.select({
      ios: { fontFamily: "AvenirNext-Heavy" },
      android: { fontFamily: "sans-serif-condensed" },
      default: {},
    }),
  },
  remainingLabel: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.2,
    color: COLORS.muted,
    textTransform: "uppercase",
  },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  favoriteButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  progressTrack: {
    height: 12,
    backgroundColor: COLORS.track,
    borderRadius: 999,
    overflow: "hidden",
    marginTop: 8,
  },
  progressFill: {
    height: "100%",
    backgroundColor: COLORS.accent,
    borderRadius: 999,
  },
  buttonRow: { flexDirection: "row", gap: 12, marginTop: 14 },
  singleButtonRow: { flexDirection: "row", marginTop: 6 },
  button: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButton: { backgroundColor: COLORS.accent },
  secondaryButton: {
    backgroundColor: COLORS.soft,
    borderWidth: 1,
    borderColor: "#E2DBD3",
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
    ...Platform.select({
      ios: { fontFamily: "AvenirNext-DemiBold" },
      android: { fontFamily: "sans-serif-medium" },
      default: {},
    }),
  },
  secondaryText: { color: COLORS.ink },
  pressed: { opacity: 0.8 },
  disabled: { opacity: 0.4 },
  note: { marginTop: 12, color: COLORS.muted },
  noteBold: { fontWeight: "700" },
  controls: { marginTop: 14, gap: 10 },
  presetSection: { gap: 8 },
  presetTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.muted,
    letterSpacing: 1.2,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionToggle: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.muted,
  },
  presetRow: { gap: 10 },
  presetGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  favoriteBarContent: {
    flexDirection: "row",
    gap: 10,
    paddingVertical: 4,
  },
  presetChip: {
    backgroundColor: COLORS.card,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#E6E0D8",
  },
  presetChipSelected: {
    backgroundColor: COLORS.accentSoft,
    borderColor: COLORS.accent,
  },
  presetChipText: { color: COLORS.ink, fontWeight: "600" },
  presetChipTextSelected: { color: COLORS.accent, fontWeight: "700" },
  row: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
    borderWidth: 1,
    borderColor: "#F3EEE7",
  },
  rowHeader: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
  toggleRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  rowLabel: { fontSize: 15, fontWeight: "600", color: COLORS.ink },
  rowValue: { fontSize: 15, fontWeight: "700", color: COLORS.ink },
  languageRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  languageRowSelected: { backgroundColor: COLORS.accentSoft, borderColor: COLORS.accent },
  languageHint: { marginTop: 2, fontSize: 12, color: COLORS.muted },
  languageCheck: { fontSize: 18, fontWeight: "800", color: COLORS.accent },
  toast: {
    position: "absolute",
    backgroundColor: COLORS.ink,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  toastHost: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
  },
  toastText: {
    color: "white",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
});
